version: '3.8'
services:
  db:
    image: mongo:latest
    container_name: db
    ports:
      - "${DB_PORT:-8080}:27017"
    volumes:
      - db_volume:/data/db
  app:
    build:
      context: .
    command: "make run"
    environment:
      _LAMBDA_SERVER_PORT: '${_LAMBDA_SERVER_PORT}'
      AWS_LAMBDA_RUNTIME_API: '${AWS_LAMBDA_RUNTIME_API}'
      DB_URI: '${DB_URI}'
      DB_DATABASE: '${DB_DATABASE}'
    volumes:
      - .:/app
    ports:
      - "${APP_PORT:-8080}:8080"
    depends_on:
      - "db"
    links:
      - "db"
volumes:
  db_volume:
    driver: local