version: '3.8'
services:
  db:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: db
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  app:
    build:
      context: .
    command: "make run"
    environment:
      APP_PORT: '${APP_PORT}'
      AWS_REGION: '${AWS_REGION}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
      AWS_SECRET_KEY: '${AWS_SECRET_KEY}'
      REGION: '${AWS_REGION}'
      DB_ENDPOINT: '${DB_ENDPOINT}'
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    links:
      - "db"
  # prod:
  #   build:
  #     context: .
  #   command: "make run-prod"
  #   environment:
  #     APP_PORT: '${APP_PORT}'
  #     AWS_REGION: '${AWS_REGION}'
  #     AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
  #     AWS_SECRET_KEY: '${AWS_SECRET_KEY}'
  #     REGION: '${AWS_REGION}'
  #     DB_ENDPOINT: '${DB_ENDPOINT}'
  #     _LAMBDA_SERVER_PORT: ''
  #     AWS_LAMBDA_RUNTIME_API: 'go1.x'
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - "db"
  #   links:
  #     - "db"