#!/bin/bash

# go test ./...

if [ "$1" = "lambda" ]; then
    RANDOM_DB_NAME=$(openssl rand -hex 6)
    export $(grep -v '^#' .env | xargs) && export DB_DATABASE=$RANDOM_DB_NAME && echo "DB: ${DB_DATABASE}" && go test ./cmd/lambda/...
else 
    export $(grep -v '^#' .env | xargs) && go test ./pkg/...
fi